pipeline {
    agent { docker { image 'node:14-alpine' } }
    stages {
        stage('build') {
            steps {
                sh 'npm --version'
            }
        }
        stage('run') {
            steps {
                sh 'node NodeJS/nodejstest.js'
            }
        }
    }
}